spring:
  application:
    name: uptime-monitor
  datasource:
    url: jdbc:postgresql://localhost:5441/uptime_monitor
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  data:
    redis:
      host: localhost
      port: 6380
    cache:
      type: redis
      redis:
        time-to-live: 60s
        cache-null-values: false

server:
  port: 8090