spring:
  application:
    name: uptime-monitor
  datasource:
    url: jdbc:postgresql://localhost:5441/uptime_monitor
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
      open-in-view: false
  flyway:
    enabled: true
  server:
    port: 8090