name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: uptime_monitor
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5441:5432
        options: >-
          --health-cmd "pg_isready -U user -d uptime_monitor"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - run: ./mvnw -B verify